document.writeln("<header id=\"mainNav\">");
document.writeln("	<nav class=\"top-nav\" data-topbar>");
document.writeln("		<ul>");
document.writeln("			<li>");
document.writeln("				<a data-page=\"1\" class=\"active\"  href=\"javascript:;\">");
document.writeln("					<i class=\"nav-item-icon\"></i>");
document.writeln("					<span class=\"nav-item-name\">我的首页</span>");
document.writeln("				</a>");
document.writeln("			</li>");
document.writeln("			<li>");
document.writeln("				<a data-page=\"2\"  href=\"javascript:;\">");
document.writeln("					<i class=\"nav-item-icon\"></i>");
document.writeln("					<span class=\"nav-item-name\">门店首页</span>");
document.writeln("				</a>");
document.writeln("			</li>");
document.writeln("			<li>");
document.writeln("				<a data-page=\"3\" class=\"disabled\">");
document.writeln("					<i class=\"nav-item-icon\"></i>");
document.writeln("					<span class=\"nav-item-name\">客户预约</span>");
document.writeln("				</a>");
document.writeln("			</li>");
document.writeln("			<li>");
document.writeln("				<a data-page=\"4\" class=\"disabled\">");
document.writeln("					<i class=\"nav-item-icon\"></i>");
document.writeln("					<span class=\"nav-item-name\">消耗开单</span>");
document.writeln("				</a>");
document.writeln("			</li>");
document.writeln("			<li>");
document.writeln("				<a data-page=\"5\" class=\"disabled\">");
document.writeln("					<i class=\"nav-item-icon\"></i>");
document.writeln("					<span class=\"nav-item-name\">工单管理</span>");
document.writeln("				</a>");
document.writeln("			</li>");
document.writeln("			<li>");
document.writeln("				<a data-page=\"6\" class=\"disabled\">");
document.writeln("					<i class=\"nav-item-icon\"></i>");
document.writeln("					<span class=\"nav-item-name\">排班</span>");
document.writeln("				</a>");
document.writeln("			</li>");
document.writeln("			<li>");
document.writeln("				<a data-page=\"7\" class=\"disabled\">");
document.writeln("					<i class=\"nav-item-icon\"></i>");
document.writeln("					<span class=\"nav-item-name\">订单管理</span>");
document.writeln("				</a>");
document.writeln("			</li>");
document.writeln("			<li>");
document.writeln("				<a data-page=\"8\" class=\"disabled\">");
document.writeln("					<i class=\"nav-item-icon\"></i>");
document.writeln("					<span class=\"nav-item-name\">客户管理</span>");
document.writeln("				</a>");
document.writeln("			</li>");
document.writeln("			<li>");
document.writeln("				<a data-page=\"9\" class=\"disabled\">");
document.writeln("					<i class=\"nav-item-icon\"></i>");
document.writeln("					<span class=\"nav-item-name\">统计报表</span>");
document.writeln("				</a>");
document.writeln("			</li>");
document.writeln("		</ul>");
document.writeln("	</nav>");
document.writeln("</header>");
