document.writeln(" <div class=\'left pull-left\'>");
document.writeln("                <div class=\'sidebar\'>");
document.writeln("                    <ul class=\'sidebar-collapse\'>");
document.writeln("                        <li>");
document.writeln("                            <a type=\'index\' class=\'sidebar-item\' href=\'index.html\'><i class=\'fa fa-home\'></i>主页</a>");
document.writeln("                        </li>");
document.writeln("                        <li>");
document.writeln("                            <a type=\'publish\' class=\'sidebar-item\' href=\'send_article.html\'><i class=\'fa fa-edit\'></i>发表</a>");
document.writeln("                        </li>");
document.writeln("                        <li>");
document.writeln("                            <a class=\'cur-d\'><i class=\'fa fa-file-text-o\'></i>文章管理</a>");
document.writeln("                            <ul class=\'sidebar-sub\'>");
document.writeln("                                <li>");
document.writeln("                                    <a type=\'report\' href=\'report.html\' class=\'sidebar-item\'>手动更新</a>");
document.writeln("                                </li>");
document.writeln("                                <li>");
document.writeln("                                    <a type=\'commentlist\' href=\'commentlist.html \' class=\'sidebar-item\'>评论管理</a>");
document.writeln("                                </li>");
document.writeln("                                <li>");
document.writeln("                                    <a type=\'question_mine\' href=\'question_mine.html \' class=\'sidebar-item\'>问答管理</a>");
document.writeln("                                </li>");
document.writeln("                                <li>");
document.writeln("                                    <a type=\'voteManage\' href=\'voteManage.html \' class=\'sidebar-item\'>投票管理</a>");
document.writeln("                                </li>");
document.writeln("                            </ul>");
document.writeln("                        </li>");
document.writeln("                        <li>");
document.writeln("                            <a class=\'cur-d\'><i class=\'fa fa-bar-chart \'></i>数据统计</a>");
document.writeln("                            <ul class=\'sidebar-sub \'>");
document.writeln("                                <li>");
document.writeln("                                    <a type=\'fans_analysis\' href=\'fans_analysis.html \' class=\'sidebar-item \'>粉丝分析</a>");
document.writeln("                                </li>");
document.writeln("                                <li>");
document.writeln("                                    <a type=\'articleAnalysis\' href=\'articleAnalysis.html \' class=\'sidebar-item \'>文章分析</a>");
document.writeln("                                </li>");
document.writeln("                            </ul>");
document.writeln("                        </li>");
// document.writeln("                        <li>");
// document.writeln("                            <a class=\'cur-d\'><i class=\'fa fa-volume-up \'></i>收益</a>");
// document.writeln("                            <ul class=\'sidebar-sub \'>");
// document.writeln("                                <li>");
// document.writeln("                                    <a type=\'income_overview\' href=\'income_overview.html \' class=\'sidebar-item \'>收益设置</a>");
// document.writeln("                                </li>");
// document.writeln("                                <li>");
// document.writeln("                                    <a type=\'income\' href=\'income.html \' class=\'sidebar-item \'>收益概览</a>");
// document.writeln("                                </li>");
// document.writeln("                                <li>");
// document.writeln("                                    <a type=\'accounting_center\' href=\'accounting_center.html \' class=\'sidebar-item \'>结算中心</a>");
// document.writeln("                                </li>");
// document.writeln("                            </ul>");
// document.writeln("                        </li>");
document.writeln("                        <li>");
document.writeln("                            <a class=\'cur-d\'><i class=\'fa fa-gear \'></i>设置</a>");
document.writeln("                            <ul class=\'sidebar-sub \'>");
document.writeln("                                <li>");
document.writeln("                                    <a type=\'accounts\' href=\'accounts.html \' class=\'sidebar-item \'>账号信息</a>");
document.writeln("                                </li>");
document.writeln("                            </ul>");
document.writeln("                        </li>");
document.writeln("                        <li>");
document.writeln("                            <a class=\'cur-d\'><i class=\'fa fa-gear \'></i>广告管理</a>");
document.writeln("                            <ul class=\'sidebar-sub \'>");
document.writeln("                                <li>");
document.writeln("                                    <a class=\'cur-d\'>自营广告管理</a>");
document.writeln("                                    <ul class=\'sidebar-sub \'>");
document.writeln("                                        <li>");
document.writeln("                                            <a type=\'ad_server\' name=\'self_support\' href=\'ad_server.html?type=1 \' class=\'sidebar-item \'>投放广告</a>");
document.writeln("                                        </li>");
document.writeln("                                        <li>");
document.writeln("                                            <a type=\'self_adHistory\' href=\'self_adHistory.html \' class=\'sidebar-item \'>投放历史</a>");
document.writeln("                                        </li>");
document.writeln("                                    </ul>");
document.writeln("                                </li>");
document.writeln("                                <li>");
document.writeln("                                    <a class=\'cur-d\'>投放广告管理</a>");
document.writeln("                                    <ul class=\'sidebar-sub \'>");
document.writeln("                                        <li>");
document.writeln("                                            <a type=\'ad_server\' name=\'platform\' href=\'ad_server.html?type=0 \' class=\'sidebar-item \'>投放广告</a>");
document.writeln("                                        </li>");
document.writeln("                                        <li>");
document.writeln("                                            <a type=\'ad_history\' href=\'ad_history.html \' class=\'sidebar-item \'>投放历史</a>");
document.writeln("                                        </li>");
document.writeln("                                    </ul>");
document.writeln("                                </li>");
document.writeln("                                <li>");
document.writeln("                                    <a type=\'cost_manage\' href=\'cost_manage.html \' class=\'sidebar-item \'>费用管理</a>");
document.writeln("                                </li>");
document.writeln("                            </ul>");
document.writeln("                        </li>");
document.writeln("                    </ul>");
document.writeln("                </div>");
document.writeln("            </div>");