document.writeln("<div class=\'container-fluet\' id=\'head\'>");
document.writeln("        <div class=\'row row-inhert\'>");
document.writeln("            <div class=\'col-md-2 row-inhert\'>");
document.writeln("            </div>");
document.writeln("            <div class=\'col-md-5 row-inhert\'>");
document.writeln("                <nav class=\'navbar head-nav\' role=\'navigation\'> ");
document.writeln("                    <div class=\'container-fluid\'> ");
document.writeln("                        <ul class=\'nav navbar-nav navbar-left ml10\'> ");
document.writeln("                            <li class=\'ml20\' id=\'contorl-left\'><a href=\'#\'><span class=\'glyphicon mr10 glyphicon-th-list\'></span>左侧</a></li> ");
document.writeln("                            <li class=\'ml20\'><a href=\'index.html\' target=\'_self\'><span class=\'glyphicon mr10 glyphicon-home\'></span>首页</a></li> ");
document.writeln("                            <li class=\'ml20\'><a href=\'#\'><span class=\'glyphicon mr10 glyphicon-off\'></span>退出</a></li> ");
document.writeln("                        </ul> ");
document.writeln("                    </div> ");
document.writeln("                </nav>");
document.writeln("            </div>");
document.writeln("            <div class=\'col-md-5 row-inhert\'>");
document.writeln("                  <nav class=\'navbar navbar-default\' role=\'navigation\'>");
document.writeln("                        <ul class=\'nav navbar-nav pull-right navbar-user p20\'>");
document.writeln("                            <li>");
document.writeln("                            </li>");
document.writeln("                            <li class=\'dropdown\'><a href=\'#\' class=\'dropdown-toggle\' data-toggle=\'dropdown\'>Javascrit <b class=\'caret\'></b></a>");
document.writeln("                                <ul class=\'dropdown-menu\'>");
document.writeln("                                    <li><a id=\'action-1\' href=\'#\'>meter</a></li>");
document.writeln("                                    <li><a href=\'#\'>EJB</a></li>");
document.writeln("                                    <li><a href=\'#\'>Jasper Report</a></li>");
document.writeln("                                    <li class=\'divider\'></li>");
document.writeln("                                    <li><a href=\'#\'>分离的链接</a></li>");
document.writeln("                                    <li class=\'divider\'></li>");
document.writeln("                                    <li><a href=\'#\'>另一个分离的链接</a></li>");
document.writeln("                                </ul>");
document.writeln("                            </li>");
document.writeln("                        </ul>");
document.writeln("                    </div>  ");
document.writeln("                </nav>");
document.writeln("            </div>");
document.writeln("        </div>");
document.writeln("    </div>");