document.writeln("<div id=\'commonEdit\' class=\'commentBox mt20\'>");
document.writeln("    <p class=\'commentBoxTit\'>评论</p>");
document.writeln("    <div class=\'commentList clearfix\'>");
document.writeln("        <img id=\'userImgIcon\' class=\'commentatorIcon fl\' src=\'img/headIcon.png\' alt=\'\'>");
document.writeln("        <div class=\'commentLCom fr\'>");
document.writeln("            <div class=\'publishCommentBox commentReplyBox clearfix\'>");
document.writeln("                <textarea id=\'publishCommentInp\' class=\'publishCommentInp commentReplyInp fl\' placeholder=\'请输入评论\'></textarea>");
document.writeln("                <div class=\'commentReplyBottom fl\'>");
document.writeln("                    <div class=\'fl\'></div>");
document.writeln("                    <button id=\'commentPublishBtn\' class=\'commentReplyBtn fr\'>发布</button>");
document.writeln("                </div>");
document.writeln("            </div>");
document.writeln("        </div>");
document.writeln("    </div>");
document.writeln("    <div id=\'commentBox\' class=\'commentBox\'></div>");
document.writeln("    <p id=\'moreCommentBtn\' class=\'moreCommentBtn cur-p\'>查看更多评论</p>");
document.writeln("</div>");