document.writeln("<div class=\'header\'>");
document.writeln("        <div class=\'container\'>");
document.writeln("            <a class=\'pageLogo fl\' href=\'index.html\'></a>");
document.writeln("            <div class=\'userOperate fr\'>");
document.writeln("                <span class=\'cur-p\' data-toggle=\'modal\' data-target=\'#loginModal\'>登录</span>");
document.writeln("                <i>/</i>");
document.writeln("                <span class=\'cur-p\' id=\'registerSpan\' data-toggle=\'modal\' data-target=\'#loginModal\'>注册</span>");
document.writeln("            </div>");
document.writeln("            <div class=\'userInfo fr dis-n\'>");
document.writeln("                <img src=\'\' alt=\'\' class=\'avatar cur-p\' id=\'avatarImg\'>");
document.writeln("                <span class=\'username cur-p\' id=\'username\'></span>");
document.writeln("                <ul class=\'dropdown\'>");
document.writeln("                    <li class=\'line\'>");
document.writeln("                        <a href=\'javascript:QC.Login.signOut();\' id=\'exit\'>");
document.writeln("                            <i class=\'fa fa-sign-out\'></i>");
document.writeln("                            <span>退出</span>");
document.writeln("                        </a>");
document.writeln("                    </li>");
document.writeln("                </ul>");
document.writeln("            </div>");
document.writeln("        </div>");
document.writeln("    </div>");