document.writeln("<div class=\'modal fade\' id=\'loginModal\' tabindex=\'-1\' role=\'dialog\'>");
document.writeln("        <div class=\'modal-dialog login-modal-dialog\' role=\'document\'>");
document.writeln("            <div class=\'modal-content login-modal-content\'>");
document.writeln("                <div class=\'login-modal-header\'>");
document.writeln("                    <ul class=\'title_ul\'>");
document.writeln("                        <li class=\'active\'>登录</li>");
document.writeln("                        <li id=\'regLi\'>注册</li>");
document.writeln("                    </ul>");
document.writeln("                </div>");
document.writeln("                <div class=\'login-modal-body\'>");
document.writeln("                    <div id=\'loginBox\' class=\'loginBox active\'>");
document.writeln("                        <form id=\'loginForm\'>");
document.writeln("                            <div class=\'login-form-control\'>");
document.writeln("                                <input type=\'text\' id=\'usercodeInp\' placeholder=\'请输入手机号\' name=\'usercode\' maxlength=\'11\'>");
document.writeln("                            </div>");
document.writeln("                            <div class=\'login-form-control\'>");
document.writeln("                                <input type=\'password\' id=\'passwordInp\' placeholder=\'请输入密码\' name=\'password\'>");
document.writeln("                            </div>");
document.writeln("                            <div class=\'rememberBox\'>");
document.writeln("                                <div class=\'fl\'>");
document.writeln("                                    <div id=\'remember\' class=\'remember fl mr10\'></div>");
document.writeln("                                    <label for=\'remember\'>下次自动登录</label>");
document.writeln("                                </div>");
document.writeln("                                <div class=\'fr\' style=\'color:#ccc;\'>忘记密码?</div>");
document.writeln("                            </div>");
document.writeln("                            <div class=\'login-form-control mt20\'>");
document.writeln("                                <div>");
document.writeln("                                    <!--<p class=\'loginP\'>使用第三方登录</p>-->");
document.writeln("                                    <a href=\'javascript:;\' id=\'loginA\'></a>");
document.writeln("                                </div>");
document.writeln("                            </div>");
document.writeln("                            <div class=\'login-form-control\'>");
document.writeln("                                <a href=\'javascript:;\' class=\'loginBtn\' id=\'loginBtn\'>登录</a>");
document.writeln("                            </div>");
document.writeln("                        </form>");
document.writeln("                    </div>");
document.writeln("                    <div id=\'registerBox\' class=\'loginBox\'>");
document.writeln("                        <form id=\'regForm\'>");
document.writeln("                            <div class=\'login-form-control font18px\'>");
document.writeln("                                <div class=\'fl mr30\'>性别:</div>");
document.writeln("                                <div class=\'label-control fl mr30 active\'> ");
document.writeln("                                    <span class=\'login-radio\'></span>");
document.writeln("                                    <span class=\'usersex\'>男</span>");
document.writeln("                                </div>");
document.writeln("                                <div class=\'label-control fl\'>");
document.writeln("                                    <span class=\'login-radio\'></span>");
document.writeln("                                    <span class=\'usersex\'>女</span>");
document.writeln("                                </div>");
document.writeln("                            </div>");
document.writeln("                            <div class=\'login-form-control\'>");
document.writeln("                                <input type=\'text\' id=\'regUsercode\' placeholder=\'请输入手机号\' name=\'usercode\' maxlength=\'11\'>");
document.writeln("                            </div>");
document.writeln("                            <div class=\'login-form-control\'>");
document.writeln("                                <input type=\'password\' id=\'regPassword\' placeholder=\'请输入密码\' name=\'password\'>");
document.writeln("                            </div>");
document.writeln("                            <div class=\'login-form-control\'>");
document.writeln("                                <a href=\'javascript:;\' class=\'codeBtn fl\' id=\'codeBtn\'>免费获取验证码</a>");
document.writeln("                                <input type=\'text\' class=\'codeTxt fl\' id=\'codeTxt\' placeholder=\'验证码\' name=\'code\'>");
document.writeln("                            </div>");
document.writeln("                            <div class=\'login-form-control\'>");
document.writeln("                                <a href=\'javascript:;\' class=\'regBtn\' id=\'regBtn\'>注册</a>");
document.writeln("                            </div>");
document.writeln("                        </form>");
document.writeln("                    </div>");
document.writeln("                </div>");
document.writeln("            </div>");
document.writeln("        </div>");
document.writeln("    </div>");