document.writeln("<div class=\'right fr\'>");
document.writeln("    <div class=\'searchInp clearfix\'>");
document.writeln("        <div class=\'tt-autocomplete\'>");
document.writeln("            <input type=\'text\' placeholder=\'大家都在搜：\' autocomplete=\'off\' class=\'tt-input__inner\' id=\'searchTxt\'>");
document.writeln("            <i class=\'tt-input__icon bui-icon glyphicon glyphicon-search\' style=\'font-size: 18px;\' id=\'searchI\'></i>");
document.writeln("        </div>");
document.writeln("        <div id=\'searchListBox\'>");
document.writeln("            <ul></ul>");
document.writeln("        </div>");
document.writeln("    </div>");
document.writeln("    <a href=\'http://www.12377.cn/node_552908.htm\' target=\'_blank\' class=\'bui-box report clearfix\'>");
document.writeln("        <div class=\'bui-left img-holder\'><img src=\'//s3a.pstatp.com/toutiao/resource/ntoutiao_web/static/image/other/report_logo_15cc24e.png\' alt=\'\'></div>");
document.writeln("        <div class=\'bui-left info\'>");
document.writeln("            <p class=\'title\'>网上有害信息举报专区</p>");
document.writeln("            <p class=\'tel\'>举报电话：12377</p>");
document.writeln("        </div>");
document.writeln("    </a>");
document.writeln("    <div class=\'hot\'>");
document.writeln("        <div class=\'r_head\'>");
document.writeln("            <h2 class=\'title\'>智享头条</h2>");
document.writeln("        </div>");
document.writeln("        <div class=\'r_list\'>");
document.writeln("            <ul id=\'rArtList\'></ul>");
document.writeln("        </div>");
document.writeln("    </div>");
document.writeln("    <!--广告-->");
document.writeln("    <div class=\'right-iframe-img right-img\'>");
document.writeln("        <!--<script src=\'//p.tanx.com/ex?i=mm_32479643_3494618_56064454\' charset=\'gbk\' id=\'tanx-s-mm_32479643_3494618_56064454\'></script>-->");
document.writeln("        <img src=\'img/gg.png\' alt=\'\'>");
document.writeln("    </div>");
document.writeln("    <!--热门视频-->");
document.writeln("    <h2 class=\'hot_title hotRSecond\'>");
document.writeln("        热门视频");
document.writeln("    </h2>");
document.writeln("    <div class=\'r_list\'>");
document.writeln("        <ul id=\'rVideoList\'></ul>");
document.writeln("    </div>");
document.writeln("    <!--广告-->");
document.writeln("    <div class=\'right-iframe-img right-img\'>");
document.writeln("        <!--<script src=\'//p.tanx.com/ex?i=mm_32479643_3494618_56064454\' charset=\'gbk\' id=\'tanx-s-mm_32479643_3494618_56064454\'></script>-->");
document.writeln("        <img src=\'img/gg.png\' alt=\'\'>");
document.writeln("    </div>");
document.writeln("    <!--热门视频-->");
document.writeln("    <h2 class=\'hot_title yellow hotPicture\'>");
document.writeln("        精彩图片");
document.writeln("    </h2>");
document.writeln("    <div class=\'wonderful clearfix hotPicture\' id=\'wonderful\'></div>");
document.writeln("    <div class=\'company\'>");
document.writeln("        <p class=\'J-company-name\'> © 2017 智享头条</p> <a href=\'javascript:;\' target=\'_blank\' ga_event=\'click_about\'>中国互联网举报中心</a>");
document.writeln("        <div>");
document.writeln("            <p></p>");
document.writeln("        </div>");
document.writeln("        <p>");
document.writeln("            <a href=\'comments.html\' target=\'_blank\'>跟帖评论自律管理承诺书</a>");
document.writeln("        </p>");
document.writeln("        <span>违法和不良信息举报：010-58341833</span>");
document.writeln("        <span>公司名称：尖叫时刻（武汉）传媒有限公司</span>");
document.writeln("    </div>");
document.writeln("                <div href=\'javascript:;\' class=\'ewmBox\'>");
document.writeln("                    下载<span class=\'red\'>智享城市</span>");
document.writeln("                    <img src=\'img/ewm.png\' alt=\'\'>");
document.writeln("                </div>");
document.writeln("                <div id=\'scrollTop\' class=\'animated zoomInRight\'>");
document.writeln("                    <img src=\'img/return.png\' alt=\'top\'>");
document.writeln("                </div>");
document.writeln("</div>");