document.writeln("<div class=\'main-top clearfix\'>");
document.writeln("            <div class=\'container\'>");
document.writeln("                <h1 class=\'logo fl\'>");
document.writeln("                    <a href=\'index.html\'></a>");
document.writeln("                </h1>");
document.writeln("                <div id=\'commonNavChild\' class=\'navChild fl\'>");
// document.writeln("                    <a href=\'index.html\'>首页</a> | <a class=\'gray\'>正文</a>");
document.writeln("                    <a href=\'index.html\' id=\'indexA\'>首页</a> | <a href=\'javascript:;\' id=\'navChildA\'></a> | <span class=\'gray\'>正文</span>");
document.writeln("                </div>");
// document.writeln("                <div class=\'searchInp fr\'>");
// document.writeln("                    <div class=\'tt-autocomplete\'>");
// document.writeln("                        <input type=\'text\' placeholder=\'大家都在搜：霍建华红毯推人\' autocomplete=\'off\' class=\'tt-input__inner\'>");
// document.writeln("                        <i class=\'tt-input__icon bui-icon glyphicon glyphicon-search\' style=\'font-size: 18px;\'></i>");
// document.writeln("                    </div>");
// document.writeln("                    <div id=\'searchListBox\'>");
// document.writeln("                        <ul></ul>");
// document.writeln("                    </div>");
// document.writeln("                </div>");
document.writeln("            </div>");
document.writeln("        </div>");