document.writeln("<div class=\"share\">");
document.writeln("                <p class=\"writerimg\"><img src=\"img/writer.png\" alt=\"\"><span></span></p>");
document.writeln("                <p class=\"fenxiangimg\"><img src=\"img/fenxiang.png\" alt=\"\"><span>分享</span></p>");
document.writeln("                <div class=\"weixin\">");
document.writeln("                    <img src=\"img/weixinfen.png\" alt=\"\">");
document.writeln("                    <div class=\"erweima animated fadeIn\" id=\"qrcode\" style=\"display: none;\">");
document.writeln("                    </div>");
document.writeln("                </div>");
document.writeln("                <p><img onclick=\"shareTo(\'qzone\')\" src=\"img/qqkj.png\" alt=\"\"></p>");
document.writeln("                <p><img onclick=\"shareTo(\'sina\')\" src=\"img/tengxun.png\" alt=\"\"></p>");
document.writeln("            </div>");