document.writeln("<!-- modal -->");
document.writeln("    <div class=\'modal fade\' id=\'change-password\' tabindex=\'-1\' role=\'dialog\' aria-labelledby=\'myModalLabel\' aria-hidden=\'true\'>");
document.writeln("    <div class=\'modal-dialog\'>");
document.writeln("        <div class=\'modal-content\'>");
document.writeln("            <div class=\'modal-header\'>");
document.writeln("                <button type=\'button\' class=\'close\' data-dismiss=\'modal\' aria-hidden=\'true\'>×");
document.writeln("                </button>");
document.writeln("                <h4 class=\'modal-title\' id=\'myModalLabel\'>");
document.writeln("                    修改密码");
document.writeln("                </h4>");
document.writeln("            </div>");
document.writeln("            <div class=\'modal-body\'>");
document.writeln("                <form class=\'bs-example bs-example-form\' role=\'form\' id=\'changeform\'>");
document.writeln("                    <div class=\'input-group change-width\'>");
document.writeln("                        <span class=\'input-group-addon change\'>旧密码</span>");
document.writeln("                        <input type=\'text\' class=\'form-control\' id=\'oldpassword\'>");
document.writeln("                    </div>");
document.writeln("                    <br>");
document.writeln("                    <br>");
document.writeln("                    <div class=\'input-group change-width\'>           ");
document.writeln("                        <span class=\'input-group-addon change\'>新密码:</span>");
document.writeln("                        <input type=\'text\' class=\'form-control\' id=\'newpassword\'>");
document.writeln("                    </div>");
document.writeln("                    <br>");
document.writeln("                    <br>");
document.writeln("                    <div class=\'input-group change-width\'>");
document.writeln("                        <span class=\'input-group-addon change\'>再次输入新密码:</span>");
document.writeln("                        <input type=\'text\' class=\'form-control\' id=\'newpassword\'>");
document.writeln("                    </div>");
document.writeln("                    <br>");
document.writeln("                    <br>");
document.writeln("                </form>");
document.writeln("            </div>");
document.writeln("            <div class=\'modal-footer\'>");
document.writeln("                <button type=\'button\' class=\'btn btn-primary close-btn\' id=\'saveParameter\' aria-hidden=\'true\'>");
document.writeln("                    保存");
document.writeln("                </button>");
document.writeln("            </div>");
document.writeln("        </div>");
document.writeln("    </div>");
document.writeln("</div>");