document.writeln("   <div class=\'container-fluet\' id=\'head\'>");
document.writeln("        <div class=\'row row-inhert\'>");
document.writeln("            <div class=\'col-xs-2 row-inhert left-logo\'>");
document.writeln("                <img src=\'common/image/zx_logo.png\' class=\'row-logo-img\' />");
document.writeln("            </div>");
document.writeln("            <div class=\'col-xs-5 row-inhert mid-config\'>");
document.writeln("                <nav class=\'navbar head-nav\' role=\'navigation\'> ");
document.writeln("                    <div class=\'container-fluid\'> ");
document.writeln("                        <ul class=\'nav navbar-nav navbar-left\'> ");
document.writeln("                            <li class=\'ml15\' id=\'contorl-left\'><a href=\'#\'><span class=\'icon-zc\'></span>左侧</a></li> ");
document.writeln("                            <li class=\'ml40\' id=\'contorl-quit\'><a href=\'#\'><span class=\'icon-tc\'></span>退出</a></li> ");
document.writeln("                        </ul> ");
document.writeln("                    </div> ");
document.writeln("                </nav>");
document.writeln("            </div>");
document.writeln("            <div class=\'col-xs-5 row-inhert navbar-right\'>");
document.writeln("                  <nav class=\'navbar navbar-default\' role=\'navigation\'>");
document.writeln("                        <ul class=\'nav navbar-nav pull-right navbar-user p20\'>");
document.writeln("                            <li>");
document.writeln("                                <img src=\'\'  alt=\'\' id=\'user-pic\' />");
document.writeln("                            </li>");
document.writeln("                            <li class=\'dropdown\'><a href=\'#\' class=\'dropdown-toggle\' data-toggle=\'dropdown\' ><span id=\'user-name\'></span> <b class=\'caret\'></b></a>");
document.writeln("                                <ul class=\'dropdown-menu\' id=\'dropdown\'>");
document.writeln("                                    <li><a id=\'changePassword\' href=\'#\' data-toggle='modal' data-target='#change-password'>修改密码</a></li><li><a id=\'quit\' href=\'#\'>退出</a></li>");
document.writeln("                                </ul>");
document.writeln("                            </li>");
document.writeln("                        </ul>");
document.writeln("                    </div>  ");
document.writeln("                </nav>");
document.writeln("            </div>");
document.writeln("        </div>");