document.writeln(" <div class=\'left pull-left\'>");
document.writeln("                <div class=\'sidebar\'>");
document.writeln("                    <ul class=\'sidebar-collapse\' id=\'leftMenuUl\'>");
// document.writeln("                        <li>");
// document.writeln("                            <a type=\'index\' class=\'sidebar-item\' href=\'index.html\'><i class=\'fa fa-home\'></i>主页</a>");
// document.writeln("                        </li>");
// document.writeln("                        <li>");
// document.writeln("                            <a class=\'cur-d\'><i class=\'fa fa-file-text-o\'></i>审核</a>");
// document.writeln("                            <ul class=\'sidebar-sub\'>");
// document.writeln("                                <li>");
// document.writeln("                                    <a type=\'authorial_check\' href=\'authorial_check.html \' class=\'sidebar-item\'>作家审核</a>");
// document.writeln("                                </li>");
// document.writeln("                                <li>");
// document.writeln("                                    <a type=\'article_check\' href=\'article_check.html \' class=\'sidebar-item\'>文章审核</a>");
// document.writeln("                                </li>");
// document.writeln("                            </ul>");
// document.writeln("                        </li>");
// document.writeln("                        <li>");
// document.writeln("                            <a class=\'cur-d\'><i class=\'glyphicon glyphicon-signal \'></i>收益审核</a>");
// document.writeln("                            <ul class=\'sidebar-sub \'>");
// document.writeln("                                <li>");
// document.writeln("                                    <a type=\'gainsToCheck\' href=\'gainsToCheck.html \' class=\'sidebar-item \'>单日收益核对</a>");
// document.writeln("                                </li>");
// document.writeln("                                <li>");
// document.writeln("                                    <a type=\'unusually\' href=\'unusually.html \' class=\'sidebar-item \'>异常名单</a>");
// document.writeln("                                </li>");
// document.writeln("                                <li>");
// document.writeln("                                    <a type=\'blacklist\' href=\'blacklist.html \' class=\'sidebar-item \'>黑名单</a>");
// document.writeln("                                </li>");
// document.writeln("                            </ul>");
// document.writeln("                        </li>");
// document.writeln("                        <li>");
// document.writeln("                            <a type=\'weight_manage\' class=\'sidebar-item\' href=\'weight_manage.html\'><i class=\'fa fa-bar-chart\'></i>作家权重管理</a>");
// document.writeln("                        </li>");
// document.writeln("                        <li>");
// document.writeln("                            <a type=\'admin_manage\' class=\'sidebar-item\' href=\'admin_manage.html\'><i class=\'glyphicon glyphicon-user\'></i>管理员管理</a>");
// document.writeln("                        </li>");
// document.writeln("                        <li>");
// document.writeln("                            <a class=\'cur-d\'><i class=\'glyphicon glyphicon-blackboard\'></i>平台管理</a>");
// document.writeln("                            <ul class=\'sidebar-sub\'>");
// document.writeln("                                <li>");
// document.writeln("                                    <a type=\'platform_manage\' href=\'platform_manage.html \' class=\'sidebar-item\'>标签维护</a>");
// document.writeln("                                </li>");
// document.writeln("                                <li>");
// document.writeln("                                    <a type=\'channel_manage\' href=\'channel_manage.html \' class=\'sidebar-item\'>频道维护</a>");
// document.writeln("                                </li>");
// document.writeln("                                <li>");
// document.writeln("                                    <a type=\'keywords\' href=\'keywords.html \' class=\'sidebar-item\'>关键词维护</a>");
// document.writeln("                                </li>");
// document.writeln("                            </ul>");
// document.writeln("                        </li>");
// document.writeln("                        <li>");
// document.writeln("                            <a type=\'subject_sitting\' class=\'sidebar-item\' href=\'subject_sitting.html\'><i class=\'glyphicon glyphicon-cog\'></i>专题设置</a>");
// document.writeln("                        </li>");
// document.writeln("                        <li>");
// document.writeln("                            <a class=\'cur-d\'><i class=\'fa fa-file-text-o\'></i>焦点设置</a>");
// document.writeln("                            <ul class=\'sidebar-sub\'>");
// document.writeln("                                <li>");
// document.writeln("                                    <a type=\'carousel_setting\' href=\'carousel_setting.html \' class=\'sidebar-item\'>轮播图设置</a>");
// document.writeln("                                </li>");
// document.writeln("                                <li>");
// document.writeln("                                    <a type=\'push_history\' href=\'push_history.html \' class=\'sidebar-item\'>推送历史</a>");
// document.writeln("                                </li>");
// document.writeln("                            </ul>");
// document.writeln("                        </li>");
// document.writeln("                    </ul>");
document.writeln("                </div>");
document.writeln("            </div>");