document.writeln("<div class=\'col-md-1 left-nav\' id=\'accordion\'>");
document.writeln("                <div class=\'list-group\'>");
document.writeln("                    <h4 class=\'list-group-item\'>");
document.writeln("                        <a data-toggle=\'collapse\' data-parent=\'#accordion\' ");
document.writeln("                        href=\'#collapseThree\'>");
document.writeln("                        账务管理");
document.writeln("                        </a>");
document.writeln("                    </h4>");
document.writeln("                    <div id=\'collapseThree\' class=\'panel-collapse collapse in\'>");
document.writeln("                        <div class=\'panel-body\'>");
document.writeln("                            <a href=\'../income/consume.html\' class=\'list-group-item\'>");
document.writeln("                                <h4 class=\'list-group-item-heading\'>");
document.writeln("                                <i class=\'jurisdiction\'></i>公司收入");
document.writeln("                                </h4>");
document.writeln("                            </a>");
document.writeln("                            <a href=\'../account/seller.html\' class=\'list-group-item\'>");
document.writeln("                                <h4 class=\'list-group-item-heading\'>");
document.writeln("                                <i class=\'jurisdiction\'></i>账户");
document.writeln("                                </h4>");
document.writeln("                            </a>");
document.writeln("                            <a href=\'../trade/audit.html\' class=\'list-group-item\'>");
document.writeln("                                <h4 class=\'list-group-item-heading\'>");
document.writeln("                                <i class=\'supervise\'></i>交易流水");
document.writeln("                                </h4>");
document.writeln("                            </a>");
document.writeln("                            <a href=\'../count/accountCount.html\' class=\'list-group-item\'>");
document.writeln("                                <h4 class=\'list-group-item-heading\'>");
document.writeln("                                <i class=\'organization\'></i>账务统计");
document.writeln("                                </h4>");
document.writeln("                            </a>");
document.writeln("                            <a href=\'../pool/cash.html\' class=\'list-group-item\'>");
document.writeln("                                <h4 class=\'list-group-item-heading\'>");
document.writeln("                                <i class=\'jurisdiction\'></i>资金池");
document.writeln("                                </h4>");
document.writeln("                            </a>");
document.writeln("                            <a href=\'../parm/model.html\' class=\'list-group-item\'>");
document.writeln("                                <h4 class=\'list-group-item-heading\'>");
document.writeln("                                <i class=\'supervise\'></i>账务参数");
document.writeln("                                </h4>");
document.writeln("                            </a>");
document.writeln("                        </div>");
document.writeln("                    </div>");
document.writeln("                </div>");
document.writeln("            </div>");