document.writeln("<div class=\'col-md-1 left-nav\' id=\'accordion\'>");
document.writeln("                <div class=\'list-group\'>");
document.writeln("                    <h4 class=\'list-group-item\'>");
document.writeln("                        <a data-toggle=\'collapse\' data-parent=\'#accordion\' ");
document.writeln("                        href=\'#collapseOne\'>");
document.writeln("                        基础设置");
document.writeln("                        </a>");
document.writeln("                    </h4>");
document.writeln("                    <div id=\'collapseOne\' class=\'panel-collapse collapse in\'>");
document.writeln("                        <div class=\'panel-body\'>");
document.writeln("                            <a href=\'#\' class=\'list-group-item active\'>");
document.writeln("                                <h4 class=\'list-group-item-heading\'>");
document.writeln("                                <i class=\'argument\'></i>");
document.writeln("                                    模板参数");
document.writeln("                                </h4>");
document.writeln("                            </a>");
document.writeln("                            <a href=\'#\' class=\'list-group-item\'>");
document.writeln("                                <h4 class=\'list-group-item-heading\'>");
document.writeln("                                <i class=\'config\'></i>");
document.writeln("                                    参数配置");
document.writeln("                                </h4>");
document.writeln("                            </a>");
document.writeln("                            <a href=\'#\' class=\'list-group-item\'>");
document.writeln("                                <h4 class=\'list-group-item-heading\'>");
document.writeln("                                <i class=\'versions\'></i>");
document.writeln("                                    版本管理");
document.writeln("                                </h4>");
document.writeln("                            </a>");
document.writeln("                        </div>");
document.writeln("                    </div>");
document.writeln("                </div>");
document.writeln("                <div class=\'list-group\'>");
document.writeln("                    <h4 class=\'list-group-item\'>");
document.writeln("                        <a data-toggle=\'collapse\' data-parent=\'#accordion\' ");
document.writeln("                        href=\'#collapseTwo\'>");
document.writeln("                        人员管理");
document.writeln("                        </a>");
document.writeln("                    </h4>");
document.writeln("                    <div id=\'collapseTwo\' class=\'panel-collapse collapse in\'>");
document.writeln("                        <div class=\'panel-body\'>");
document.writeln("                            <a href=\'#\' class=\'list-group-item\'>");
document.writeln("                                <h4 class=\'list-group-item-heading\'>");
document.writeln("                                <i class=\'role\'></i>");
document.writeln("                                    系统角色");
document.writeln("                                </h4>");
document.writeln("                            </a>");
document.writeln("                            <a href=\'#\' class=\'list-group-item\'>");
document.writeln("                                <h4 class=\'list-group-item-heading\'>");
document.writeln("                                <i class=\'jurisdiction\'></i>");
document.writeln("                                    权限管理");
document.writeln("                                </h4>");
document.writeln("                            </a>");
document.writeln("                            <a href=\'#\' class=\'list-group-item\'>");
document.writeln("                                <h4 class=\'list-group-item-heading\'>");
document.writeln("                                <i class=\'supervise\'></i>");
document.writeln("                                    用户管理");
document.writeln("                                </h4>");
document.writeln("                            </a>");
document.writeln("                            <a href=\'#\' class=\'list-group-item\'>");
document.writeln("                                <h4 class=\'list-group-item-heading\'>");
document.writeln("                                <i class=\'organization\'></i>");
document.writeln("                                    系统组织");
document.writeln("                                </h4>");
document.writeln("                            </a>");
document.writeln("                        </div>");
document.writeln("                    </div>");
document.writeln("                </div>");
document.writeln("                <div class=\'list-group\'>");
document.writeln("                    <h4 class=\'list-group-item\'>");
document.writeln("                        <a data-toggle=\'collapse\' data-parent=\'#accordion\' ");
document.writeln("                        href=\'#collapseThree\'>");
document.writeln("                        账务管理");
document.writeln("                        </a>");
document.writeln("                    </h4>");
document.writeln("                    <div id=\'collapseThree\' class=\'panel-collapse collapse in\'>");
document.writeln("                        <div class=\'panel-body\'>");
document.writeln("                            <a href=\'#\' class=\'list-group-item\'>");
document.writeln("                                <h4 class=\'list-group-item-heading\'>");
document.writeln("                                <i class=\'jurisdiction\'></i>");
document.writeln("                                    <a href=\'../income/consume.html\'>公司收入</a>");
document.writeln("                                </h4>");
document.writeln("                            </a>");
document.writeln("                            <a href=\'#\' class=\'list-group-item\'>");
document.writeln("                                <h4 class=\'list-group-item-heading\'>");
document.writeln("                                <i class=\'jurisdiction\'></i>");
document.writeln("                                    <a href=\'../account/seller.html\'>账户</a>");
document.writeln("                                </h4>");
document.writeln("                            </a>");
document.writeln("                            <a href=\'#\' class=\'list-group-item\'>");
document.writeln("                                <h4 class=\'list-group-item-heading\'>");
document.writeln("                                <i class=\'supervise\'></i>");
document.writeln("                                    <a href=\'../trade/audit.html\'>交易流水</a>");
document.writeln("                                </h4>");
document.writeln("                            </a>");
document.writeln("                            <a href=\'#\' class=\'list-group-item\'>");
document.writeln("                                <h4 class=\'list-group-item-heading\'>");
document.writeln("                                <i class=\'organization\'></i>");
document.writeln("                                    <a href=\'../count/accountCount.html\'>账务统计</a>");
document.writeln("                                </h4>");
document.writeln("                            </a>");
document.writeln("                            <a href=\'#\' class=\'list-group-item\'>");
document.writeln("                                <h4 class=\'list-group-item-heading\'>");
document.writeln("                                <i class=\'jurisdiction\'></i>");
document.writeln("                                   <a href=\'../pool/cash.html\'>资金池</a>");
document.writeln("                                </h4>");
document.writeln("                            </a>");
document.writeln("                            <a href=\'#\' class=\'list-group-item\'>");
document.writeln("                                <h4 class=\'list-group-item-heading\'>");
document.writeln("                                <i class=\'supervise\'></i>");
document.writeln("                                    <a href=\'../parm/model.html\'>账务参数</a>");
document.writeln("                                </h4>");
document.writeln("                            </a>");
document.writeln("                        </div>");
document.writeln("                    </div>");
document.writeln("                </div>");
document.writeln("            </div>");